### ISSUE TITLE
Feature request: tg read-only mode

### ISSUE THREAD

**Issue by crypt1d** [ledgerwatch/turbo-geth#1168]
Current implementation of `--chaindata` for the rpcdaemon leaves a lot to be desired, since many RPC call are not available in this mode. This is rather unfortunate because it still requires us to run the main tg daemon and pass requests over the network interface(twice). If we could at least have a tg mode which disables all features but the `private.api`, that would at least make it significantly less resource intensive (I assume).

**Comment by AlexeyAkhunov** [comment]
Hi @crypt1d We are not planning to have JSON RPC API exposed on the TG process itself, because we think it does not really belong there. Instead, we do have private api, which is essentially read only access to its database in the live mode. If your application is very demanding to performance and is sensitive to latencies between RPC daemon and TG, then you should be looking into using the private api directly, I think. Unfortunately, for this you will need to know the data model. And though we have started documenting it and make examples, it is far from complete.
Please refer to the architecture plans for some reasons why RPC daemon is separate: https://github.com/AlexeyAkhunov/papers/blob/master/Turbo-Geth-Silkworm-architecture-plans.pdf

**Comment by crypt1d** [comment]
Thank you @AlexeyAkhunov . My apologizes, I think I may have poorly expressed myself.

Currently if one wants to get the 'full' JSON RPC, one has to run the TG daemon and the RPC daemon AND connect them over the TCP network. The RPC daemon has a `--chaindata` switch which would normally allow it to bypass the connection to the TG daemon and read the data from disk directly, but currently this mode does not support all JSON RPC functions (eg net_version or trace functions).

This kinda sucks because with `--chaindata` you can work with disk snapshots and you don't need to run the main TG process, which is pretty CPU intensive because it keeps syncing with the network. If we could find a way to force the TG process to work in a mode which disables all functions (eg peering, syncing, etc) except the private api, that would let us run a very lightweight solution for use cases like reading historical data from the blockchain. The JSON RPC requests would still go through the rpcdaemon. Its just that the TG process would only serve the private API requests and do nothing else.

I guess in theory I could  achieve the same thing by blocking peering connections via a firewall, and only allow API requests. But I would certainly appreciate a more elegant solution baked into TG itself.

I hope that makes sense!

**Comment by AlexeyAkhunov** [comment]
`--chaindata` is designed only for debugging purposes, at least now. We sometimes use to debug, because we know the database won't change while we are testing. There is no plan to try to support all the features, but all the things that only require the database should actually work, including reading historical data. Which specific methods don't work for you that you think they should?

**Comment by tjayrush** [comment]
@crypt1d This table https://github.com/ledgerwatch/turbo-geth/tree/master/cmd/rpcdaemon#rpc-implementation-status has three or four items marked 'remote only'. I think these are the only calls (other than those not implemented) that don't work with `--chaindata`. If there are others, let me know, and I will add them.

**Comment by crypt1d** [comment]
I think my biggest pet peeve is `eth_getLogs`, but I'm not sure if that can work with the database only?

**Comment by AlexeyAkhunov** [comment]
`eth_getLogs` should be able to work with the database now, this has changed a few days ago. But I will double-check

**Comment by AlexeyAkhunov** [comment]
I am going to close this, please open if this is still an issue
