### ISSUE TITLE
Rearrange some of the code in ./cmd/rpcdaemon

### ISSUE THREAD

**Issue by tjayrush** [ledgerwatch/turbo-geth#1224]
As part of this process #1209, I'd like to move a few functions around in the `./cmd/rpcdaemon` folder. It will make doing automated testing and perhaps some automated code generation easier if the testing suite and the code are more consistent.

I'll make a WIP PR to track. Not sure if small PRs or one larger one is better. Advice?

**Comment by AlexeyAkhunov** [comment]
I do not have a preference. If you can make lots of changes quickly, then perhaps one large PR is better. If you want to make it easier to review, I think git supports `git mv` command or something that takes into account that moved files and changed them rather than just removed one file and added another

**Comment by tjayrush** [comment]
There's a current PR (#1225) that you can merge now, and then I will move things using `git mv` all at once but not change any of the code. I made suggestions about how I'd like to re-arrange things here: https://github.com/ledgerwatch/turbo-geth/blob/1224-rearrange-rpc-code/cmd/rpcdaemon/commands/eth_api.go#L26
