### ISSUE TITLE
How do I use the cache flag? 

### ISSUE THREAD

**Issue by ratacat** [ledgerwatch/turbo-geth#1405]
I've tried issuing it as an commandline option `--cache="5000" but that doesn't work. In `tg --help` it shows --cachSize, but in the [tg godoc](https://godoc.org/github.com/ledgerwatch/turbo-geth/cmd/utils#pkg-index) it shows 'cache' very clearly. Any one figured this out?

In general I'm trying to get things optimized to run well on a very large server to (hopefully) minimize the time disruption processing certain blocks.

**Comment by mandrigin** [comment]
`—help` is programmatically generated from the actually supported flags, so I’d trust this one.

**Comment by mandrigin** [comment]
I’m not sure though if the cache will do anything for a fast machine (if not make things worse), I guess @AlexeyAkhunov could help there.

**Comment by ratacat** [comment]
Okay...server has 16 cores and 128gb of ram. I just want to make sure that tg is using everything it can to be optimized for speed!

**Comment by AskAlexSharov** [comment]
@ratacat , don't worry too much, because TG's database (LMDB) is basically is MMAP file. MMAP file performance heavily rely on OS page cache (aka "virtual memory of process") and OS will use all available RAM for this and elastically free it if RAM is needed in another part of system at the moment. So, TG will use all your RAM, this memory will belongs to OS instead of TG.
in short - for now, stick with defaults is good enough.

cores - here we are less effitient for now, only few parts of TG are using multi-core. Most of TG is single-core, but it's not because it lack parallelism, but because it is Disk bounded - not CPU bounded, and adding parallelism to Disk-bounded tasks will make things worse. But Raid may help here - see more info about it in our #testing chat.

**Comment by ratacat** [comment]
Thankyou Alex, much appreciated!
