### ISSUE TITLE
Another dumb question: How to tell syncing progress? (eth.syncing seems not to work)

### ISSUE THREAD

**Issue by ratacat** [ledgerwatch/turbo-geth#1408]
Title pretty much says it all...from rpc with eth.syncing I get
```
> eth.syncing
{
  currentBlock: 0,
  highestBlock: 11439276,
  startingBlock: 0
}
```

Any ideas how to tell progress?

**Comment by AskAlexSharov** [comment]
TG progress is more complex than Geth's - because it pass all blocks which need to process through many stages. For example if you syncing 10 blocks - you can't say that processing of block 1 is done until all 10 blocks are passed all stages. 

Means first it downloading all 10 blocks at once, then execute all 10 blocks at once, then calculate merkle hash root for all 10 blocks at once, then building various indices for all 10 block at once. When block 1 is done?

So, it's possible to show progress but not in terms of "done blocks" - at least not for genesis sync or startup after long downtime.

So, please determine what kind of progress you wanna tell?
