### ISSUE TITLE
Error: MDB_CORRUPTED: Located page was wrong type

### ISSUE THREAD

**Issue by ChosunOne** [ledgerwatch/turbo-geth#1473]
#### System information

TG version: f20c08d18b477f10fbbaf49ac6dea52722f7ec4a
OS & Version: Ubuntu Server 20.04
Commit hash : f20c08d18b477f10fbbaf49ac6dea52722f7ec4a

#### Expected behaviour
I upgraded from 1828bb32faff1778e14e48703307cef9f43aefea to f20c08d18b477f10fbbaf49ac6dea52722f7ec4a on the master branch, using the same database.  

#### Actual behaviour
Things seemed to work fine for a few days until today, where I am stuck with the following error:
```
Synchronisation failed, retrying         err="2/14 BlockHashes: put: k=dede8b9166645c34c82c9fbab1516c2eb8d24ef880f1360760963a677569e1ab, mdb_cursor_put: MDB_CORRUPTED: Located page was wrong type"
```

#### Steps to reproduce the behaviour
Sync on the above mentioned commit hash, then after a full sync upgrade to the latter commit hash and wait.

**Comment by erthink** [comment]
If I understand correctly, then this is a LMDB bug (not the MDBX), then seems it is the time for switch from [LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database) to [`libmdbx`](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database).
Otherwise, @AskAlexSharov, please let me know immediately and provide an into to reproduce the problem.

**Comment by AskAlexSharov** [comment]
@erthink , i think it’s lmdb.

**Comment by AskAlexSharov** [comment]
@ChosunOne it’s true. We are planing to switch TurboGeth from LMDB to MDBX. Partially because  we have facing db corruptions (in very rare cases), and because lmdb has no tool to detect corruptions or to check db. 

I think now it’s safe for you to switch to mdbx (we will make it default in near future). You can do it by: remove existing datadir, add flag —database=mdbx when run TurboGeth. 

 Thank you for understanding. We can investigate problem by getting your db file, but it will take long time.

**Comment by ChosunOne** [comment]
@AskAlexSharov Thanks for the quick update. I've already removed the datadir and switched to geth for the time being. I'll try turbo geth again after issues with database corruption have been resolved (likely when mdbx is made default).

**Comment by AskAlexSharov** [comment]
Then just read our future release notes ;-)
