### ISSUE TITLE
RPC daemon: Implement debug_storageRangeAt

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#226]
Current implementation here:
https://github.com/ledgerwatch/turbo-geth/blob/28d9b7c8126567814544455a436a7566de117011/eth/api.go#L408

**Comment by AskAlexSharov** [comment]
This method contains write operations. They are in `https://github.com/ledgerwatch/turbo-geth/blob/28d9b7c8126567814544455a436a7566de117011/eth/api_tracer.go#L702` - inside `statedb.FinalizeTx` function.

- Can rpcdaemon perform db changes? 
- I also see code like `vm.NewEVM` - can rpcdaemon do something related to EVM? 
- From my point of view need replace `api.computeTxEnv` by `api.computeIntraBlockState`, because `computeTxEnv returns the execution environment of a certain transaction` but we didn't plan to execute any transactions. Is it bad idea?

**Comment by AskAlexSharov** [comment]
done
