### ISSUE TITLE
Introduce INTERMEDIATE_HASHES bucket - Phase 1

### ISSUE THREAD

**Issue by AlexeyAkhunov** [ledgerwatch/turbo-geth#311]
Create a new bucket in the database. Its purpose it is going to be to complement the current state buckets (`dbutils.AccountsBucket` and `dbutils.StorageBucket`). These current state buckets contain the mappings:
`hash_of_address_of_account => serialised_account`
`hash_of_address_of_account|incarnation|hash_of_storage_position => storage_value`

this is the main difference between turbo-geth and geth . This representation makes a lot of things faster and more straightforward, but it makes other things much harder.
The state on the Ethereum mainnet is very large, and we cannot assume that we can hold it entirely in memory. That is why there will be part of the state we hold in memory (cache), in the form of the patricia merkle tree, and the part of the state, which is not in that cache. Important property of such cache is that it is always possible to recompute the state root from the information in the cache.

If we are to satisfy state modification that goes beyond what it is in the cache, we first need to bring the required part of the state into the cache, and also some extra information that will allow us to preserve the property of being able to compute the state root. We currently call the process of loading this required part of the state (+extra information to be able to compute the state root) from the database to the cache - Resolution. It is implemented in `trie/resolver.go` and `trie/hashbuilder.go`. The main problem with the resolution is that often it needs to load a lot of records from the database, only to compute the hash of the subtree, and discard the read records. This is especially visible when the turbo-geth is restarted, and it needs to compute the state root of the Entire state, which means it needs to read the entire `AccountsBucket`.

To address this problem, we would like to experiment with adding an extra bucket to the database. In this bucket, we will store the mappings:
`some_prefix_of(hash_of_address_of_account) => hash_of_subtrie`
`hash_of_address_of_account|incarnation|some_prefix_of(hash_of_storage_position) => hash_of_subtrie`

We do not want to store this information for all possible subtries in the state trie. There are two restrictions:
1. We only store the hashes of subtries starting on the branch nodes (`fullNode` and `duoNode` in `trie/node.go`)
2. We only store the hashes that are not currently in the memory cache.

The reason for the second restriction is to prevent a high level of "churn" in the database. The hashes on the top of the state trie change very often, so we want it to happen only in our memory cache, and not in the database. But things we do not have in the memory cache, might become useful when we reach to the "cold" (as in not in the cache) parts of the state.

In the first stage, we only want to populate this bucket, but not use it yet for speeding up the "Resolution". Here are the suggested insertion points:

1. Function `ResolveStateTrie` in the `core/state/database.go` performs the "Resolution" process. It is split up into 2 parts - one for the accounts (`buildAccountsTouches` and `resolveAccountsTouches`), another - for storage (`buildStorageTouches` and `resolveStorageTouches`). In the functions `resolveAccountsTouches` and `resolveStorageTouches` you can see the use of `Resolver` type from `trie/resolver.go`. Function `ResolveWithDb` is what performs the actual resolution (access to the database, if necessary). At this point, we would like to detect which branch nodes (`fullNode` and `branchNode`) we have brought into the memory cache, and **delete** them from our Intermediate Hash bucket (because they will now possibly change in memory).
2. Function `PruneTries` in the `core/state/database.go` unloads parts of the memory cache, those parts that have not been touched for longest. It is done by the function `PruneTo` defined in `trie/trie_pruning.go`. We would like to detect those branch nodes (`fullNode` and `branchNode`) that have been unloaded and **insert** them into our Intermediate Hash bucket (because they will not change for a while, and will help us to recover parts of the state quicker later).

**Comment by AlexeyAkhunov** [comment]
Initial suggestion for the key to be used in the new bucket. First byte is the number of "digits" in the prefix (since we use hexary tree, one digit is 4 bits). Other bytes are the digits of the prefix, possibly padded by one empty hex digit.
We might discover other key formats that work better

**Comment by AskAlexSharov** [comment]
## Preface: 
“Nibbles sequences of various limited length” form totally different Set compare to “Bytes of fixed length”. Take a look: 

![1](https://user-images.githubusercontent.com/46885206/72720740-32730080-3bad-11ea-8702-4d16d36752c9.jpg)

fmt.Sprintf(“%x”) - does follow same Hex logic - after x00 goes x01, but not x0000
This is reason why we can't just smash nibbles n0,n1 to byte x01: between n0 and n0,n1 exists n0,n0 - while between x00 and x01 doesn't exist anything.

#### Definitions:
Nibbles - Set of “Nibbles sequences of various limited length”
Bytes - Set of “Bytes sequences of various limited length”
N - Max length of Nibbles (dimension)
L - length of given nibbles sequence
Ordering property - lexicographical ordering of elements must be same before and after mapping
Compact property - result bytes must take as less space as possible
Mapping - mapping from Set 1 to Set 2 which preserve ordering

Our target is to construct "Mapping of sets which preserving **Ordering** and **Compact**" (mapping from “Nibbles sequences of various limited length” to “Bytes sequences of fixed length” or to “Bytes sequences of various length"). 

## Step 1: Construction of mapping which preserve ordering. 

Let's switch to limited dimension - because our task is about hashes prefixes. I will draw pictures for Dimension=3 and provide formulas for Dimension=N.

To show that problem is solvable: let's construct mapping from Nibbles and set of "Natural numbers". 

![2](https://user-images.githubusercontent.com/46885206/72720807-50d8fc00-3bad-11ea-8f4e-cf837dfd228d.jpg)

For example nibble n1 has number: 16^2 + 16 + 1. Common formula:

![3](https://user-images.githubusercontent.com/46885206/72721582-f80a6300-3bae-11ea-9e4c-d9e538374a08.jpg)

Just open bracers and sum similar powers to get right part of formula (1). Mapping from Bytes to Natural numbers looks same - just change 16 to 256. 

Constructed mapping of Bytes and Nibbles to Natural numbers preserving Ordering but not Compact. But it's enough to show that we can map Nibbles to Bytes and preserve Ordering (just choose 2 elements from 2 sets which relate to same Natural number). 

Formula (1) has another property: it places all images of Nibbles as close to 0 as possible. In Step 2 we will sacrifice this property to achieve Compact. 

## Step 2: Compaction 

To achieve it - make sure that all shortest target bytes are used and we still have enough space between elements to put any source prefixes without breaking ordering. 

How much bytes we need to encode nibbles of max length L? `16^n+16^(n-1)+...+1 = 256^(n/2)+256^(n/2 - 1)+... < 256^(n/2 + 1)` - then required `N/2 + 1` of Bytes.

![4](https://user-images.githubusercontent.com/46885206/72722805-cfd03380-3bb1-11ea-81d4-61f459b48281.jpg)
ToDo: provide better quality of picture^

ToDo: add final formula 

ToDo: link to implementation and benchmarks (Status: fixing bugs)

**Comment by AskAlexSharov** [comment]
Agreed to store only nibbles of even length. Done.
