### ISSUE TITLE
De-hash Change Sets

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/turbo-geth#423]
in our ChangeSet buckets, we currently have address hashes and storage key hashes + corresponding values
and they are sorted by those values, so we can find an item by binary search easily
there was another potential use case for the ChangeSets. When (and if) we get to support of LES protocol (light clients), we will need to produce merkle proofs of some accounts and storage items which are not current, but slightly in the past
so what we will do is to extract the proof as if it was for the current state
and then try to apply ChangeSets backwards until we get to the required point in history
I initially thought that we might be able to avoid applying the entire ChangeSets, and instead apply only the bits around the accounts and storage items we need. But this thinking is flawed, as i understand now
so we will need to apply entire ChangeSets backwards
So, now is the idea
I wonder if we can use addresses (instead of address Hashes) and storage keys (instead of storage key hashes) in the ChangeSets
the reason it would be attractive is that you can split out preimage generation as a separate step, which does not have to happen at the same time as the block execution (currently it does)
Meaning we can have following stages of sync:
1. Download headers
2. Download block bodies
3. Execute blocks (generate ChangeSets and final state and receipts).
And then optional stages
4. Generate preimages
5. Generate tx lookups

And, by extension, the indices can also be based on addresses and storage keys rather than on address hashes and storage key hashes
it will speed up the tx tracing tiny bit, at the expense of slower reorgs

**Comment by AlexeyAkhunov** [comment]
While writing WalkAsOf implementation for THIN_HISTORY, I realised that we won't be able to support WalkAsOf in the current way if we do the De-Hashing.

Because the way we do WalkAsOf relies on walking simultaneously over the current state (which uses hashes) and the history (which also uses hashes, but would use preimages if we do De-hashing)
so I think we won't do it for the Release1. The way to make it work is to also maintain the De-hashed version of the current state. this might be interesting direction to explore, but it is definitely much more work than we want to do for the first release
