### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by paulmillr** [ledgerwatch/turbo-geth#606]
Hi. What's the status of turbo-geth? Is it nearing stable release? Is it going to be merged into geth after some time?

**Comment by AlexeyAkhunov** [comment]
Hi Paul. We are very near the first release, yes. We would have released earlier, but we discovered a way to drastically reduce the initial sync time for the node (that is sync from genesis, not the fast sync).
No, the code is not going to be merged back into geth, because turbo-geth is essentially becoming a very different product. The divergence is growing quickly and it will likely to continue to diverge.

**Comment by paulmillr** [comment]
Is there any particular reason why turbo-geth cannot be merged back? Some lack of a feature?

**Comment by AlexeyAkhunov** [comment]
Hi Paul, the reason why I cannot be merged back is mostly of my perception. The code differences and architecture differences are very large. I do not want to shepherd the process of merging back with go-ethereum, because I think it will take a very long time and energy, and possible never complete. They do, however, cherry-pick some improvements from our code base

**Comment by paulmillr** [comment]
Understood. I’ll ask them myself once turbo is out then.
