### ISSUE TITLE
block not found for eth_getBlockByNumber and eth_getBlockByHash

### ISSUE THREAD

**Issue by koen84** [ledgerwatch/turbo-geth#958]
`eth_getBlockByNumber` and `eth_getBlockByHash`
both come back with "block not found".

I'm running the 2020-08-03 release on Ubuntu 18.04 LTS.

**Comment by AskAlexSharov** [comment]
TurboGeth by design has no http interface (still has A bit because it’s hard to delete). To get RPC you need: 1. Start TG 2. Start separated process which we call “RPCDaemon” it will connect to TG by binary low-level protocol and provide for you HTTP RPC. 

Please follow this readme: https://github.com/ledgerwatch/turbo-geth/blob/master/cmd/rpcdaemon/Readme.md

And “rpcdaemon” section of main readme.

**Comment by koen84** [comment]
@AskAlexSharov uhm, that's what i did, hence i have rpcdaemon parameters.  (BTW, i like the separate approach.)

@Giulio2002 well, someone in the same project wrote a patch for eth_getBlockByHash (which i've manually updated and applied to v2020-08-03), which is probably why it didn't throw errors for me.

**Comment by Giulio2002** [comment]
@koen84 try updating to master rpcdaemon and try again, i implemented eth_getblockbyhash so you can try it again
